env:
  browser: true
  es6: true
  node: true

extends:
  - google
  - plugin:@typescript-eslint/recommended
  - plugin:eslint-plugin-import/errors
  - plugin:eslint-plugin-import/warnings
  - plugin:eslint-plugin-import/typescript

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - "@typescript-eslint"

rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^[_]+$"
      argsIgnorePattern: "^[_]+$"
      ignoreRestSiblings: true

  indent:
    - error
    - 2
    - MemberExpression: 1

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  max-len:
    - 2
    - code: 120

  no-unused-vars: 'off'
